Repository cse110-sp24-group22/cse110-sp24-group22, pull requests merged in 2024-06, with the labels that each got.

#29 add tag input (can delete/edit) and ability to save tags
  src/css/list.css
  src/html/list.html
  src/scripts/list.js
Labels: Feature

#105 Update list.css
  src/css/list.css
Labels: improvement

#121 New alert logic
  src/scripts/list.js
  src/scripts/main.js
Labels: bug, high priority, improvement

#132 Change coverage test option to E2E with puppeteer-to-istanbul
  .github/workflows/jest.e2e.cjs
  package.json
  src/tests/e2e.test.js
Labels: documentation

#125 Team page
  src/html/home.html
Labels: documentation

#120 E2E Testing added to main-doc
  .github/workflows/e2e.yml
  .github/workflows/jest.e2e.cjs
  .github/workflows/jest.e2eList.cjs
  .github/workflows/jest.e2eRoot.cjs
  .gitignore
  package.json
  src/html/home.html
  src/scripts/list.js
  src/scripts/main.js
  src/tests/e2e.testList.js
  src/tests/e2e.testRoot.js
Labels: documentation, help wanted, high priority

#142 fixed logo alignment issue
  src/html/home.html
  src/html/list.html
Labels: bug, high priority

#143 save journal for ctrl+s and command+s
  index.html
  src/scripts/list.js
  src/scripts/main.js
Labels: Feature, low priority, improvement

#147 reformatted import/exports at the top of list and util.js
  docs/JournalFilterer.html
  docs/global.html
  docs/index.html
  docs/list.js.html
  docs/main.js.html
  docs/util.js.html
  src/scripts/list.js
  src/scripts/main.js
  src/scripts/util.js
Labels: low priority, improvement

#152 Add JSDoc front page
  .github/workflows/Lint&Doc.yml
  .github/workflows/lighthouse.yml
  .github/workflows/lighthouserc.json
  docs/JournalFilterer.html
  docs/global.html
  docs/index.html
  docs/list.js.html
  docs/main.js.html
  docs/readme.md
  docs/util.js.html
  jest-puppeteer.cjs
Labels: documentation
